import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ReminderApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Reminder</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <div className={styles.cardItem}>
              <div className={styles.cardItemIcon}>
                <Image
                  src="/icons/calendar.svg"
                  width="36px"
                  height="36px"
                  alt="Calendar"   
                />            
              </div>
              <span className={styles.cardItemDate}>31</span>
              <div className={styles.cardItemText}>
                <h4 className={styles.text}>Alisson</h4>
                <h4 className={styles.text}>20/04/2002</h4>
                <h4 className={styles.text}>19 anos</h4>
              </div>
            </div>
            <div className={styles.cardItem}>
              <div className={styles.cardItemIcon}>
                <Image
                  src="/icons/calendar.svg"
                  width="36px"
                  height="36px"
                  alt="Calendar"   
                />            
              </div>
              <span className={styles.cardItemDate}>31</span>
              <div className={styles.cardItemText}>
                <h4 className={styles.text}>Alisson</h4>
                <h4 className={styles.text}>20/04/2002</h4>
                <h4 className={styles.text}>19 anos</h4>
              </div>
            </div>
            <div className={styles.cardItem}>
              <div className={styles.cardItemIcon}>
                <Image
                  src="/icons/calendar.svg"
                  width="36px"
                  height="36px"
                  alt="Calendar"   
                />            
              </div>
              <span className={styles.cardItemDate}>31</span>
              <div className={styles.cardItemText}>
                <h4 className={styles.text}>Alisson</h4>
                <h4 className={styles.text}>20/04/2002</h4>
                <h4 className={styles.text}>19 anos</h4>
              </div>
            </div>
            <div className={styles.cardItem}>
              <div className={styles.cardItemIcon}>
                <Image
                  src="/icons/calendar.svg"
                  width="36px"
                  height="36px"
                  alt="Calendar"   
                />            
              </div>
              <span className={styles.cardItemDate}>31</span>
              <div className={styles.cardItemText}>
                <h4 className={styles.text}>Alisson</h4>
                <h4 className={styles.text}>20/04/2002</h4>
                <h4 className={styles.text}>19 anos</h4>
              </div>
            </div>
            <div className={styles.cardItem}>
              <div className={styles.cardItemIcon}>
                <Image
                  src="/icons/calendar.svg"
                  width="36px"
                  height="36px"
                  alt="Calendar"   
                />            
              </div>
              <span className={styles.cardItemDate}>31</span>
              <div className={styles.cardItemText}>
                <h4 className={styles.text}>Alisson</h4>
                <h4 className={styles.text}>20/04/2002</h4>
                <h4 className={styles.text}>19 anos</h4>
              </div>
            </div>
            <div className={styles.cardItem}>
              <div className={styles.cardItemIcon}>
                <Image
                  src="/icons/calendar.svg"
                  width="36px"
                  height="36px"
                  alt="Calendar"   
                />            
              </div>
              <span className={styles.cardItemDate}>31</span>
              <div className={styles.cardItemText}>
                <h4 className={styles.text}>Alisson</h4>
                <h4 className={styles.text}>20/04/2002</h4>
                <h4 className={styles.text}>19 anos</h4>
              </div>
            </div>
            <div className={styles.cardItem}>
              <div className={styles.cardItemIcon}>
                <Image
                  src="/icons/calendar.svg"
                  width="36px"
                  height="36px"
                  alt="Calendar"   
                />            
              </div>
              <span className={styles.cardItemDate}>31</span>
              <div className={styles.cardItemText}>
                <h4 className={styles.text}>Alisson</h4>
                <h4 className={styles.text}>20/04/2002</h4>
                <h4 className={styles.text}>19 anos</h4>
              </div>
            </div>
            <div className={styles.cardItem}>
              <div className={styles.cardItemIcon}>
                <Image
                  src="/icons/calendar.svg"
                  width="36px"
                  height="36px"
                  alt="Calendar"   
                />            
              </div>
              <span className={styles.cardItemDate}>31</span>
              <div className={styles.cardItemText}>
                <h4 className={styles.text}>Alisson</h4>
                <h4 className={styles.text}>20/04/2002</h4>
                <h4 className={styles.text}>19 anos</h4>
              </div>
            </div>
            <div className={styles.cardItem}>
              <div className={styles.cardItemIcon}>
                <Image
                  src="/icons/calendar.svg"
                  width="36px"
                  height="36px"
                  alt="Calendar"   
                />            
              </div>
              <span className={styles.cardItemDate}>31</span>
              <div className={styles.cardItemText}>
                <h4 className={styles.text}>Alisson</h4>
                <h4 className={styles.text}>20/04/2002</h4>
                <h4 className={styles.text}>19 anos</h4>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
