import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  const data = await fetch("http://127.0.0.1:5000/pessoas");
  const pessoas = await data.json();
  // console.log(pessoas);
  return {
    props: {
      pessoas,
    },
  };
}


export default function Home({ pessoas }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>ReminderApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Reminder</a>
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            {pessoas.map((pessoa) => (
              <div key={pessoa.id} className={styles.cardItem}>
                <div className={styles.cardItemIcon}>
                  <Image
                    src="/icons/calendar.svg"
                    width="36px"
                    height="36px"
                    alt="Calendar"
                  />
                </div>
                <span className={styles.cardItemDate}>31</span>
                <div className={styles.cardItemText}>
                  <h4 className={styles.text}>{pessoa.nome}</h4>
                  <h4 className={styles.text}>{pessoa.data_nascimento}</h4>
                  <h4 className={styles.text}>idade</h4>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
